// Generated by gencpp from file aras_cam_daq/matlab_data.msg
// DO NOT EDIT!


#ifndef ARAS_CAM_DAQ_MESSAGE_MATLAB_DATA_H
#define ARAS_CAM_DAQ_MESSAGE_MATLAB_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace aras_cam_daq
{
template <class ContainerAllocator>
struct matlab_data_
{
  typedef matlab_data_<ContainerAllocator> Type;

  matlab_data_()
    : header()
    , encoders()
    , forces()
    , fk()
    , motor_cmd()
    , time_stamps()  {
    }
  matlab_data_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , encoders(_alloc)
    , forces(_alloc)
    , fk(_alloc)
    , motor_cmd(_alloc)
    , time_stamps(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _encoders_type;
  _encoders_type encoders;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _forces_type;
  _forces_type forces;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _fk_type;
  _fk_type fk;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _motor_cmd_type;
  _motor_cmd_type motor_cmd;

   typedef std::vector<uint64_t, typename ContainerAllocator::template rebind<uint64_t>::other >  _time_stamps_type;
  _time_stamps_type time_stamps;





  typedef boost::shared_ptr< ::aras_cam_daq::matlab_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aras_cam_daq::matlab_data_<ContainerAllocator> const> ConstPtr;

}; // struct matlab_data_

typedef ::aras_cam_daq::matlab_data_<std::allocator<void> > matlab_data;

typedef boost::shared_ptr< ::aras_cam_daq::matlab_data > matlab_dataPtr;
typedef boost::shared_ptr< ::aras_cam_daq::matlab_data const> matlab_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aras_cam_daq::matlab_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aras_cam_daq::matlab_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aras_cam_daq::matlab_data_<ContainerAllocator1> & lhs, const ::aras_cam_daq::matlab_data_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.encoders == rhs.encoders &&
    lhs.forces == rhs.forces &&
    lhs.fk == rhs.fk &&
    lhs.motor_cmd == rhs.motor_cmd &&
    lhs.time_stamps == rhs.time_stamps;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aras_cam_daq::matlab_data_<ContainerAllocator1> & lhs, const ::aras_cam_daq::matlab_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aras_cam_daq

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::aras_cam_daq::matlab_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aras_cam_daq::matlab_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aras_cam_daq::matlab_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aras_cam_daq::matlab_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aras_cam_daq::matlab_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aras_cam_daq::matlab_data_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aras_cam_daq::matlab_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d4d267f9647b57736b8787d57b74de03";
  }

  static const char* value(const ::aras_cam_daq::matlab_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd4d267f9647b5773ULL;
  static const uint64_t static_value2 = 0x6b8787d57b74de03ULL;
};

template<class ContainerAllocator>
struct DataType< ::aras_cam_daq::matlab_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aras_cam_daq/matlab_data";
  }

  static const char* value(const ::aras_cam_daq::matlab_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aras_cam_daq::matlab_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64[]                  encoders\n"
"float64[]                  forces\n"
"float64[]                  fk\n"
"float64[]                  motor_cmd\n"
"uint64[]		   time_stamps\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::aras_cam_daq::matlab_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aras_cam_daq::matlab_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.encoders);
      stream.next(m.forces);
      stream.next(m.fk);
      stream.next(m.motor_cmd);
      stream.next(m.time_stamps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct matlab_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aras_cam_daq::matlab_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aras_cam_daq::matlab_data_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "encoders[]" << std::endl;
    for (size_t i = 0; i < v.encoders.size(); ++i)
    {
      s << indent << "  encoders[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.encoders[i]);
    }
    s << indent << "forces[]" << std::endl;
    for (size_t i = 0; i < v.forces.size(); ++i)
    {
      s << indent << "  forces[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.forces[i]);
    }
    s << indent << "fk[]" << std::endl;
    for (size_t i = 0; i < v.fk.size(); ++i)
    {
      s << indent << "  fk[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.fk[i]);
    }
    s << indent << "motor_cmd[]" << std::endl;
    for (size_t i = 0; i < v.motor_cmd.size(); ++i)
    {
      s << indent << "  motor_cmd[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.motor_cmd[i]);
    }
    s << indent << "time_stamps[]" << std::endl;
    for (size_t i = 0; i < v.time_stamps.size(); ++i)
    {
      s << indent << "  time_stamps[" << i << "]: ";
      Printer<uint64_t>::stream(s, indent + "  ", v.time_stamps[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARAS_CAM_DAQ_MESSAGE_MATLAB_DATA_H
